### ISSUE TITLE
Even layout cuts off part of the Header

### ISSUE THREAD

**Issue by OlgaDernovska** [llooker/viz-report-table-marketplace#1]
Not sure if it is expected, but that is how it looks:
Auto 
<img width="482" alt="Screen Shot 2020-09-23 at 18 24 25" src="https://user-images.githubusercontent.com/49953457/94047606-373a2500-fdca-11ea-98d0-4f2f78989e31.png">
Even
<img width="524" alt="Screen Shot 2020-09-23 at 18 24 44" src="https://user-images.githubusercontent.com/49953457/94047636-402af680-fdca-11ea-9fc7-2d1d8fdd00c6.png">
this happens with "automatic column width" option on

**Comment by thomasbanghart** [comment]
Hey @OlgaDernovska! Jon put in a fix for this -- we still truncate text with ellipses but will break spaces onto new lines. If this was not quite what you had in mind feel free to open this back up and we can take another look. Thanks!
