### ISSUE TITLE
Fiscal Quarter does not show correctly when pivoted

### ISSUE THREAD

**Issue by bheltzel** [llooker/viz-report-table-marketplace#4]
![image](https://user-images.githubusercontent.com/16830555/94068906-0b5c7680-fdad-11ea-91ed-61ce7986ac9d.png)

It shows correctly when not pivoted.
There is a fiscal_month_offset: 3 applied here so the month being shown on the pivot is not actually correct either. Not sure where this value is coming from.

**Comment by bheltzel** [comment]
looks like it is not just Fiscal. doesn't seem to show the correct rendered_value from Quarter either. internal repro [here](https://demo.looker.com/explore/thelook/order_items?qid=oqOZ4iCYc51ROXgP9tvR8t&toggle=pik,vis)

**Comment by thomasbanghart** [comment]
Hey @bheltzel Jon put in a PR to fix this -- should be resolved in marketplace version. Let us know if this continues to be an issue! Thanks!
